### ISSUE TITLE
Integration entry reload needed daily

### ISSUE THREAD

**Issue by maxakash** [rkzofficial/ha-miraie-ac#14]
Hi
I have to reload the integration entry daily to make it work.
Due to this my automations fails as devices become unavailable.
Please look into this.
Thanks

**Comment by rkzofficial** [comment]
> Hi
> I have to reload the integration entry daily to make it work.
> Due to this my automations fails as devices become unavailable.
> Please look into this.
> Thanks

Could you please let me know which version of the integration you are using? If you are not using the latest version, I kindly request you to update to the latest version. This issue was previously identified in earlier versions of the integration, but it has been resolved in the most recent version.

I have personally been testing it for over a week now, and I haven't had to restart it even once.

**Comment by rkzofficial** [comment]
I have also updated the version for this integration. Kindly ensure that you are using version 1.0.3.

**Comment by maxakash** [comment]
Ok thanks, I have updated to the latest version just now.
