### ISSUE TITLE
Swing Mode

### ISSUE THREAD

**Issue by Amit-Shan** [rkzofficial/ha-miraie-ac#2]
Could you add the 5 swing positions for the AC? Highest, Lowest, Middle 1, Middle 2, Middle 3.

**Comment by Kir4Kun** [comment]
@alexeidrekker Could you please tell me which AC model you have?

**Comment by alexeidrekker** [comment]
Model: CS-CU-NU12XKYWA

**Comment by alexeidrekker** [comment]
> @alexeidrekker Could you please tell me which AC model you have?

Also, the fan mode on the integration has an "off" setting. This actually turns on the "quiet" fan speed.

**Comment by Kir4Kun** [comment]
@alexeidrekker The underlying library have these options already available 
https://github.com/Kir4Kun/miraie-ac/blob/main/miraie_ac/enums.py

HA does not have built-in presets for this modes, that's why those modes are not available in HA, I have to figure out how we to add custom presets.
I will try to do it in my free time.

**Comment by Kir4Kun** [comment]
> > @alexeidrekker Could you please tell me which AC model you have?
> 
> Also, the fan mode on the integration has an "off" setting. This actually turns on the "quiet" fan speed.

MirAIe does not have Fan off options.

**Comment by sparsh308** [comment]
Yes quiet mode is named as OFF that should be renamed
